from __future__ import annotations

from typing import Optional

from ..geometry import BoundingBox, Point, Vector
from .canvas import ArcSeg, Circle, Poly, Seg, Text


def _f(v: float) -> str:
    """Format a float compactly (up to 4 decimals, no trailing zeros)."""
    if abs(v) < 1e-10:
        return "0"
    s = f"{v:.4f}".rstrip("0").rstrip(".")
    return "0" if s in ("-0", "") else s


def _esc(s: str) -> str:
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def _dash_attr(dash: tuple[float, ...] | None) -> str:
    if not dash:
        return ""
    return f' stroke-dasharray="{" ".join(_f(d) for d in dash)}"'

_FALLBACK_FONT = "Georgia, 'Times New Roman', serif"


def items_bbox(items: list[tuple[Optional[str], object]]) -> BoundingBox:
    """Axis-aligned bounding box of all primitives, with a rough text estimate."""
    box = BoundingBox()
    for _, prim in items:
        if isinstance(prim, Seg):
            box.include_point(prim.p1)
            box.include_point(prim.p2)
        elif isinstance(prim, Poly):
            for p in prim.points:
                box.include_point(p)
        elif isinstance(prim, Circle):
            r = prim.radius
            box.include_point(Point(prim.center.x - r, prim.center.y - r))
            box.include_point(Point(prim.center.x + r, prim.center.y + r))
        elif isinstance(prim, ArcSeg):
            for p in _sample_arc(prim):
                box.include_point(p)
        elif isinstance(prim, Text):
            w = len(prim.text) * prim.size * 0.62
            h = prim.size * 1.1
            x0, x1 = {
                "start": (prim.pos.x - h * 0.2, prim.pos.x + w),
                "end": (prim.pos.x - w, prim.pos.x + h * 0.2),
                "middle": (prim.pos.x - w / 2.0, prim.pos.x + w / 2.0),
            }[prim.halign]
            box.include_point(Point(x0, prim.pos.y - h / 2.0))
            box.include_point(Point(x1, prim.pos.y + h / 2.0))
    return box


def _sample_arc(a: ArcSeg, step_deg: float = 6.0):
    n = max(2, int(abs(a.sweep_deg) / step_deg) + 1)
    return [
        a.center
        + Vector.from_polar(a.start_deg + i * a.sweep_deg / (n - 1), a.radius)
        for i in range(n)
    ]


def render_svg(items: list[tuple[Optional[str], object]], margin: float, paper: str | None) -> str:
    """Serialize tagged primitives to an SVG string with a fitted viewBox.

    World space is y-up; the emitted SVG flips y so diagrams read naturally.
    """
    box = items_bbox(items)
    if box.is_empty:
        raise ValueError("nothing to render: the scene has no drawable content")
    box = box.padded(margin)

    width, height = box.width, box.height
    y0 = box.max_y

    def X(x: float) -> str:
        return _f(x - box.min_x)

    def Y(y: float) -> str:
        return _f(y0 - y)

    out: list[str] = []
    out.append(
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {_f(width)} {_f(height)}" '
        f'width="{round(width * 96)}" height="{round(height * 96)}">'
    )
    out.append('<desc>Generated by physdraw</desc>')
    if paper:
        out.append(
            f'<rect x="0" y="0" width="{_f(width)}" height="{_f(height)}" fill="{paper}"/>'
        )

    current_group: Optional[str] = None
    for gid, prim in items:
        if gid != current_group:
            if current_group is not None:
                out.append("</g>")
            if gid is not None:
                out.append(f'<g id="{_esc(gid)}">')
            current_group = gid
        out.append(_emit(prim, X, Y))
    if current_group is not None:
        out.append("</g>")

    out.append("</svg>")
    return "\n".join(out)


def _emit(prim: object, X, Y) -> str:
    if isinstance(prim, Seg):
        return (
            f'<line x1="{X(prim.p1.x)}" y1="{Y(prim.p1.y)}" '
            f'x2="{X(prim.p2.x)}" y2="{Y(prim.p2.y)}" '
            f'stroke="{prim.color}" stroke-width="{_f(prim.width)}"'
            f'{_dash_attr(prim.dash)} stroke-linecap="round"/>'
        )

    if isinstance(prim, Poly):
        pts = " ".join(f"{X(p.x)},{Y(p.y)}" for p in prim.points)
        tag = "polygon" if prim.close else "polyline"
        attrs = [f'points="{pts}"']
        attrs.append(f'fill="{prim.fill}"' if prim.fill else 'fill="none"')
        if prim.stroke:
            attrs.append(
                f'stroke="{prim.stroke}" stroke-width="{_f(prim.width)}"'
                f'{_dash_attr(prim.dash)} stroke-linejoin="round"'
            )
        return f"<{tag} {' '.join(attrs)}/>"

    if isinstance(prim, Circle):
        attrs = [f'cx="{X(prim.center.x)}" cy="{Y(prim.center.y)}" r="{_f(prim.radius)}"']
        attrs.append(f'fill="{prim.fill}"' if prim.fill else 'fill="none"')
        if prim.stroke:
            attrs.append(f'stroke="{prim.stroke}" stroke-width="{_f(prim.width)}"')
        return f"<circle {' '.join(attrs)}/>"

    if isinstance(prim, ArcSeg):
        p_start = prim.center + Vector.from_polar(prim.start_deg, prim.radius)
        p_end = prim.center + Vector.from_polar(prim.end_deg, prim.radius)
        large = 1 if abs(prim.sweep_deg) > 180.0 else 0
        # y-flip mirrors orientation: ccw in world becomes cw in svg.
        sweep_flag = 0 if prim.sweep_deg > 0 else 1
        d = (
            f"M {X(p_start.x)} {Y(p_start.y)} "
            f"A {_f(prim.radius)} {_f(prim.radius)} 0 {large} {sweep_flag} "
            f"{X(p_end.x)} {Y(p_end.y)}"
        )
        return (
            f'<path d="{d}" fill="none" stroke="{prim.color}" '
            f'stroke-width="{_f(prim.width)}"{_dash_attr(prim.dash)}/>'
        )
    if isinstance(prim, Text):
        anchor = {"start": "start", "middle": "middle", "end": "end"}[prim.halign]
        style = []
        if prim.italic:
            style.append('font-style="italic"')
        if prim.bold:
            style.append('font-weight="bold"')
        style_s = " ".join(style)
        rot = (
            f' transform="rotate({_f(-prim.rotation_deg)} {X(prim.pos.x)} {Y(prim.pos.y)})"'
            if prim.rotation_deg
            else ""
        )
        return (
            f'<text x="{X(prim.pos.x)}" y="{Y(prim.pos.y)}" '
            f'font-family="{_esc(prim.font_family or _FALLBACK_FONT)}" '
            f'font-size="{_f(prim.size)}" fill="{prim.color}" text-anchor="{anchor}" '
            f'dominant-baseline="central" {style_s}{rot}>{_esc(prim.text)}</text>'
        )
    raise TypeError(f"unknown primitive type: {type(prim)!r}")
